### ISSUE TITLE
getting exception on parser.Unseal 

### ISSUE THREAD

**Issue by ipoonawala1** [google-pay/payment-data-cryptography-dotnet#7]
The code works well on my local machine, but when we put on our test server we are getting below exception. Please help identifying this issue.

Exception Message - One or more errors occurred. (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond).
 
Stack Trace
System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at GooglePay.PaymentDataCryptography.SignatureVerification.VerifyMessage(PaymentData paymentData, String sender, String recipient, ISignatureKeyProvider keyProvider) in D:\Agents\a1\_work\36\s\src\GooglePay.PaymentDataCryptography\SignatureVerification.cs:line 38
   at GooglePay.PaymentDataCryptography.PaymentMethodTokenRecipient.Unseal(String sealedMessage) in D:\Agents\a1\_work\36\s\src\GooglePay.PaymentDataCryptography\PaymentMethodTokenRecipient.cs:line 122

**Comment by fstanis** [comment]
It seems your server is blocking external HTTP requests that are needed to fetch Google's signing keys.

You have two options:

1.  Configure your test server to allow external traffic to `https://payments.developers.google.com` which is needed to fetch these keys.

2.  Make Google's signing keys available on your test server through other means (e.g. locally) and then load them by extending [ISignatureKeyProvider](https://github.com/google-pay/payment-data-cryptography-dotnet/blob/master/GooglePay.PaymentDataCryptography/ISignatureKeyProvider.cs). For an example on how to do this, see how [GoogleKeyProvider](https://github.com/google-pay/payment-data-cryptography-dotnet/blob/master/GooglePay.PaymentDataCryptography/GoogleKeyProvider.cs) works.

I'm closing this since it's not an issue with the library.
